mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.personcs.usercenter.mybatis.entity
server:
  port=8080
spring:
  datasource:
    username: root
    password: 123456qhnan
    url: jdbc:mysql://localhost:3308/usercenter?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值